export type FieldDef = {
  key: string;
  label: string;
  help: string;
  required: boolean;
  step: 1 | 2 | 3;
  example: string;
};

// Single source of truth: wizard inputs, CSV template + in-UI upload guide all render from this.
export const FIELDS: FieldDef[] = [
  { key: "revenue", label: "Revenue (sales)", help: "Total sales in the period, in Rs. The base for most ratios.", required: true, step: 1, example: "1000000" },
  { key: "total_income", label: "Total income", help: "Revenue + other income (interest, rent, gains).", required: true, step: 1, example: "1100000" },
  { key: "total_expenses", label: "Total expenses", help: "All costs incl. tax. Must be > 0.", required: true, step: 1, example: "900000" },
  { key: "operating_income", label: "Operating income", help: "Profit from core business only (excl. other income).", required: false, step: 1, example: "150000" },
  { key: "operating_expenses", label: "Operating expenses", help: "Day-to-day running costs (rent, salaries, utilities).", required: false, step: 1, example: "100000" },
  { key: "net_income", label: "Net income", help: "Final profit after everything. Negative if loss-making.", required: false, step: 1, example: "120000" },
  { key: "continuous_net_income", label: "Recurring net income", help: "Net income excluding one-time gains/losses. Use net income if unsure.", required: false, step: 1, example: "110000" },
  { key: "pretax_income", label: "Profit before tax", help: "Profit before deducting tax.", required: false, step: 1, example: "140000" },
  { key: "ebit", label: "EBIT", help: "Earnings before interest and tax. Model checks if it covers interest.", required: false, step: 1, example: "160000" },
  { key: "total_assets", label: "Total assets", help: "Everything the business owns. Must be > 0.", required: true, step: 2, example: "2000000" },
  { key: "current_assets", label: "Current assets", help: "Cash + stock + receivables usable within a year.", required: false, step: 2, example: "800000" },
  { key: "quick_assets", label: "Quick assets", help: "Cash + receivables only (no stock). Emergency cover.", required: false, step: 2, example: "400000" },
  { key: "cash", label: "Cash in hand/bank", help: "Most critical liquidity signal. Never leave blank if you know it.", required: false, step: 2, example: "150000" },
  { key: "inventory", label: "Inventory / stock", help: "Goods held for sale. 0 for service businesses.", required: false, step: 2, example: "200000" },
  { key: "receivables", label: "Receivables", help: "Money customers owe you.", required: false, step: 2, example: "200000" },
  { key: "operating_cash_flow", label: "Operating cash flow", help: "Cash actually generated by operations. Negative if burning cash.", required: false, step: 2, example: "80000" },
  { key: "total_liability", label: "Total liabilities", help: "Everything the business owes.", required: false, step: 3, example: "900000" },
  { key: "current_liability", label: "Current liabilities", help: "Dues payable within a year (suppliers, short loans).", required: false, step: 3, example: "500000" },
  { key: "interest_bearing_debt", label: "Interest-bearing debt", help: "Loans that charge interest. Optional: defaults to total liabilities (safer).", required: false, step: 3, example: "600000" },
  { key: "equity", label: "Equity (own funds)", help: "Assets minus liabilities. Your own stake in the business.", required: true, step: 3, example: "1100000" },
  { key: "paid_in_capital", label: "Paid-in capital", help: "Money owners originally invested. Must be > 0.", required: true, step: 3, example: "500000" },
  { key: "retained_earnings", label: "Retained earnings", help: "Profits saved over years. Negative if accumulated losses.", required: false, step: 3, example: "300000" },
  { key: "interest_expense", label: "Interest expense", help: "Interest paid on loans in the period.", required: false, step: 3, example: "50000" },
  { key: "contingent_liability", label: "Contingent liabilities", help: "Guarantees / possible dues (court cases, LCs). 0 if none.", required: false, step: 3, example: "20000" },
];

export const REQUIRED_KEYS = FIELDS.filter((f) => f.required).map((f) => f.key);

export const CSV_HEADERS = FIELDS.map((f) => f.key).join(",");

// "10,00,000" / " 5000 " -> 1000000. Returns null when empty or not a number.
export function cleanNumber(raw: string | number | null | undefined): number | null {
  if (raw === null || raw === undefined) return null;
  const s = String(raw).replace(/[,_\s]/g, "");
  if (s === "" || s === "-" || s === ".") return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : NaN as unknown as null;
}

export function labelOf(key: string): string {
  return FIELDS.find((f) => f.key === key)?.label || key;
}
